# Generated by Django 2.0 on 2020-08-12 08:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaiArts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('artist', models.CharField(max_length=50)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=250, unique=models.CharField(max_length=50))),
                ('upload', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('body', models.TextField()),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
    ]
