# Generated by Django 3.1 on 2020-08-17 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saiarts',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('exibited', 'Exibited')], default='created', max_length=10),
        ),
    ]
